/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/search/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Search Results
     * @description Returns search results for given search string.
     *     :return: List of search results
     */
    post: operations["get_search_results_search__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/graph-view/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Graph For File
     * @description Endpoint for graph view.
     *
     *     Output is f.i.:
     *
     *     ```
     *         {
     *           "piegraphdata": [
     *             [
     *               "dn Dīghanikāya",
     *               "62063"
     *             ],
     *             [
     *               "mn Majjhimanikāya",
     *               "54783"
     *             ],
     *             [
     *               "an Aṅguttaranikāya",
     *               "24871"
     *             ],
     *
     *             ...
     *
     *             ]
     *           ],
     *           "histogramgraphdata": [
     *             [
     *               "Kūṭadanta Sutta (Dn 5)",
     *               "36982"
     *             ],
     *             [
     *               "Caṅkī Sutta (Mn 95)",
     *               "19661"
     *             ],
     *             [
     *               "Bhesajjakkhandhaka (Pli-tv-kd 6)",
     *               "7773"
     *             ],
     *             etc.
     *     ```
     *
     *     If the histogramgraphdata is null, it means that the dataset is too large to display the histogram.
     *     Please display a message asking the user to use the filters to reduce the dataset size.
     */
    post: operations["get_graph_for_file_graph_view__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/download/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Table Download
     * @description Endpoint for the download table & numbers view. Accepts filters.
     *     :return: List of segments and parallels for the downloaded table- and numbers view.
     *
     *     sort_method options:
     *
     *         "position": "By Position in Inquiry Text"
     *
     *             (matches sorted by segment number position in the root text (default))
     *
     *         "quotedtext": "By Position in Hit Text(s)"
     *
     *             (matches sorted by segment number position in the target/quoted text)
     *
     *         "length": "By Length of match in Inquiry Text (beginning with the longest)"
     *
     *             (matches sorted by match-length in the root text
     *
     *         "length2": "By Length of match in Hit Text (beginning with the longest)"
     *
     *             (matches sorted by match-length in the target/quoted text)
     *
     *     "download_data" options:
     *
     *         "table": a download is requested in table-view mode. (default)
     *
     *         "numbers": a download is requested in numbers-view mode.
     */
    post: operations["get_table_download_download__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/table-view/table/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Table View
     * @description Endpoint for the table view. Accepts filters.
     *     :return: List of segments and parallels for the table view.
     *
     *     sort_method options:
     *
     *         "position": "By Position in Inquiry Text"
     *
     *             (matches sorted by segment number position in the root text (default))
     *
     *         "quotedtext": "By Position in Hit Text(s)"
     *
     *             (matches sorted by segment number position in the target/quoted text)
     *
     *         "length": "By Length of match in Inquiry Text (beginning with the longest)"
     *
     *             (matches sorted by match-length in the root text
     *
     *         "length2": "By Length of match in Hit Text (beginning with the longest)"
     *
     *             (matches sorted by match-length in the target/quoted text)
     */
    post: operations["get_table_view_table_view_table__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/text-view/middle/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Parallels For Middle
     * @description :return: List of parallels for text view (middle)
     */
    post: operations["get_parallels_for_middle_text_view_middle__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/text-view/text-parallels/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get File Text Segments And Parallels
     * @description Endpoint for text view. Returns preformatted text segments and ids of the corresponding parallels.
     */
    post: operations["get_file_text_segments_and_parallels_text_view_text_parallels__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/numbers-view/numbers/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Numbers View
     * @description Endpoint for numbers view.
     */
    post: operations["get_numbers_view_numbers_view_numbers__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/numbers-view/categories/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Categories For Numbers View
     * @description Endpoint that returns list of categories for the given language
     */
    get: operations["get_categories_for_numbers_view_numbers_view_categories__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/links/external/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get External Links
     * @description Returns the external links for a given filename or segmentnr.
     */
    get: operations["get_external_links_links_external__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utils/count-matches/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Counts For File
     * @description Returns number of filtered parallels
     */
    post: operations["get_counts_for_file_utils_count_matches__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utils/folios/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Folios For File
     * @description Returns number of folios (TIB) / facsimiles (CHN) /
     *     suttas/PTS nrs/segments (PLI) / segments (SKT)
     */
    get: operations["get_folios_for_file_utils_folios__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/utils/displayname/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Displayname For Segmentnr
     * @description Returns the displayname for a given segmentnr or filename
     */
    get: operations["get_displayname_for_segmentnr_utils_displayname__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/menudata/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Data For Sidebar Menu
     * @description Endpoint for Menudata, formerly known as the sidebar menu.
     */
    get: operations["get_data_for_sidebar_menu_menudata__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Root
     * @description Root API endpoint
     *     :return: The response (json object)
     */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Category */
    Category: {
      /** Category */
      category: string;
      /** Categorydisplayname */
      categorydisplayname: string;
      /** Categorysearch Field */
      categorysearch_field: string;
      /** Files */
      files: components["schemas"]["File"][];
    };
    /** Collection */
    Collection: {
      /** Collection */
      collection: string;
      /** Categories */
      categories: components["schemas"]["Category"][];
    };
    /** CountMatchesInput */
    CountMatchesInput: {
      /** Filename */
      filename: string;
      filters?: components["schemas"]["Filters"];
    };
    /** CountMatchesOutput */
    CountMatchesOutput: {
      /** Parallel Count */
      parallel_count: number;
    };
    /** DisplayNameOutput */
    DisplayNameOutput: {
      /** Displayname */
      displayname: string[];
    };
    /**
     * DownloadData
     * @description An enumeration.
     * @enum {string}
     */
    DownloadData: "table" | "numbers";
    /** DownloadInput */
    DownloadInput: {
      /** Filename */
      filename: string;
      filters: components["schemas"]["Filters"];
      /**
       * Page
       * @default 0
       */
      page: number;
      /** @default position */
      sort_method: components["schemas"]["SortMethod"];
      /**
       * Folio
       * @default
       */
      folio: string;
      /** @default table */
      download_data: components["schemas"]["DownloadData"];
    };
    /**
     * DownloadOutput
     * Format: binary
     */
    DownloadOutput: string;
    /** File */
    File: {
      /** Displayname */
      displayName: string;
      /** Filename */
      filename: string;
      /** Search Field */
      search_field: string;
    };
    /**
     * Filters
     * @description Filters for matches
     */
    Filters: {
      /**
       * Par Length
       * @default 0
       */
      par_length: number;
      /**
       * Score
       * @default 0
       */
      score: number;
      languages?: components["schemas"]["Languages"][];
      /** Include Files */
      include_files?: string[];
      /** Exclude Files */
      exclude_files?: string[];
      /** Include Categories */
      include_categories?: string[];
      /** Exclude Categories */
      exclude_categories?: string[];
      /** Include Collections */
      include_collections?: string[];
      /** Exclude Collections */
      exclude_collections?: string[];
    };
    /** FolioOutput */
    FolioOutput: {
      /** Folios */
      folios: unknown[];
    };
    /** FullMatchText */
    FullMatchText: {
      /** Text */
      text: string;
      /**
       * Highlightcolor
       * @default 0
       */
      highlightColor: number;
      /** Matches */
      matches: string[];
    };
    /** FullNames */
    FullNames: {
      /** Display Name */
      display_name: string;
      /** Text Name */
      text_name: string;
    };
    /** FullText */
    FullText: {
      /** Text */
      text: string;
      /**
       * Highlightcolor
       * @default 0
       */
      highlightColor: number;
    };
    /** GeneralInput */
    GeneralInput: {
      /** Filename */
      filename: string;
      filters: components["schemas"]["Filters"];
      /**
       * Page
       * @default 0
       */
      page: number;
      /** @default position */
      sort_method: components["schemas"]["SortMethod"];
      /**
       * Folio
       * @default
       */
      folio: string;
    };
    /** GraphData */
    GraphData: {
      /** Piegraphdata */
      piegraphdata: (string | number)[][];
      /** Histogramgraphdata */
      histogramgraphdata?: (string | number)[][];
    };
    /**
     * GraphFilters
     * @description Filters for graph
     */
    GraphFilters: {
      /**
       * Par Length
       * @default 0
       */
      par_length: number;
      /**
       * Score
       * @default 0
       */
      score: number;
      /** Include Collections */
      include_collections?: string[];
    };
    /** GraphInput */
    GraphInput: {
      /** Filename */
      filename: string;
      filters: components["schemas"]["GraphFilters"];
    };
    /** GraphViewOutput */
    GraphViewOutput: components["schemas"]["GraphData"];
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Languages
     * @description An enumeration.
     * @enum {string}
     */
    Languages: "all" | "bo" | "sa" | "pa" | "zh";
    /** LinksOutput */
    LinksOutput: {
      /** Bdrc */
      bdrc: string;
      /** Rkts */
      rkts: string;
      /** Gretil */
      gretil: string;
      /** Dsbc */
      dsbc: string;
      /** Cbeta */
      cbeta: string;
      /** Suttacentral */
      suttacentral: string;
      /** Cbc */
      cbc: string;
      /** Vri */
      vri: string;
    };
    /** MenuItem */
    MenuItem: {
      /** Id */
      id: string;
      /** Displayname */
      displayName: string;
    };
    /** MenuOutput */
    MenuOutput: components["schemas"]["MenuItem"][];
    /** MenudataOutput */
    MenudataOutput: {
      /** Menudata */
      menudata: components["schemas"]["Collection"][];
    };
    /** NumbersViewOutput */
    NumbersViewOutput: components["schemas"]["api__endpoints__models__numbers_view_models__Segment"][];
    /** Parallel */
    Parallel: {
      /** Segmentnr */
      segmentnr: string;
      /** Displayname */
      displayName: string;
      /** Filename */
      fileName: string;
      /** Category */
      category: string;
    };
    /**
     * SearchFilters
     * @description Filters for search
     */
    SearchFilters: {
      language: components["schemas"]["Languages"];
      /** Include Files */
      include_files?: string[];
      /** Exclude Files */
      exclude_files?: string[];
      /** Include Categories */
      include_categories?: string[];
      /** Exclude Categories */
      exclude_categories?: string[];
      /** Include Collections */
      include_collections?: string[];
      /** Exclude Collections */
      exclude_collections?: string[];
    };
    /** SearchInput */
    SearchInput: {
      /** Search String */
      search_string: string;
      filters: components["schemas"]["SearchFilters"];
    };
    /** SearchOutput */
    SearchOutput: {
      /** Searchresults */
      searchResults: components["schemas"]["SearchResults"][];
    };
    /** SearchResults */
    SearchResults: {
      /** Category */
      category: string;
      /** Language */
      language: string;
      /** Segment Nr */
      segment_nr: string;
      full_names: components["schemas"]["FullNames"];
      /** Similarity */
      similarity: number;
      /** Segtext */
      segtext: components["schemas"]["FullText"][];
    };
    /**
     * SortMethod
     * @description An enumeration.
     * @enum {string}
     */
    SortMethod: "position" | "quotedtext" | "length" | "length2";
    /** TableViewOutput */
    TableViewOutput: components["schemas"]["api__endpoints__models__table_view_models__Segment"][];
    /** TextItem */
    TextItem: {
      /** Segnr */
      segnr: string;
      /** Segtext */
      segtext: components["schemas"]["FullMatchText"][];
    };
    /** TextParallelsInput */
    TextParallelsInput: {
      /** Filename */
      filename: string;
      /**
       * Folio
       * @default
       */
      folio: string;
      /**
       * Active Segment
       * @default none
       */
      active_segment: string;
      filters?: components["schemas"]["Filters"];
      /**
       * Page
       * @default 0
       */
      page: number;
    };
    /** TextViewLeftOutput */
    TextViewLeftOutput: {
      /** Page */
      page: number;
      /** Total Pages */
      total_pages: number;
      /** Items */
      items: components["schemas"]["TextItem"][];
    };
    /** TextViewMiddleInput */
    TextViewMiddleInput: {
      /** Parallel Ids */
      parallel_ids: unknown[];
    };
    /** TextViewMiddleOutput */
    TextViewMiddleOutput: components["schemas"]["api__endpoints__models__text_view_models__Segment"][];
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** Segment */
    api__endpoints__models__numbers_view_models__Segment: {
      /** Segmentnr */
      segmentnr: string;
      /** Parallels */
      parallels: components["schemas"]["Parallel"][];
    };
    /** Segment */
    api__endpoints__models__table_view_models__Segment: {
      /** Par Segnr Range */
      par_segnr_range: string;
      par_full_names: components["schemas"]["FullNames"];
      root_full_names: components["schemas"]["FullNames"];
      /** Root Segnr Range */
      root_segnr_range: string;
      /** Par Length */
      par_length: number;
      /** Root Length */
      root_length: number;
      /** Score */
      score: number;
      /** Src Lang */
      src_lang: string;
      /** Tgt Lang */
      tgt_lang: string;
      /** Root Fulltext */
      root_fulltext: components["schemas"]["FullText"][];
      /** Par Fulltext */
      par_fulltext: components["schemas"]["FullText"][];
    };
    /** Segment */
    api__endpoints__models__text_view_models__Segment: {
      /** Id */
      id: string;
      /** Par Segnr Range */
      par_segnr_range: string;
      /** Par Segnr */
      par_segnr: string;
      /** Display Name */
      display_name?: string;
      /** Tgt Lang */
      tgt_lang: string;
      /**
       * Par Segtext
       * @default []
       */
      par_segtext: unknown[];
      /** Filename */
      filename: string;
      /** Score */
      score: number;
      /** Length */
      length: number;
      /** Par Fulltext */
      par_fulltext?: components["schemas"]["FullText"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_search_results_search__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["SearchOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_graph_for_file_graph_view__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GraphInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["GraphViewOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_table_download_download__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DownloadInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["DownloadOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_table_view_table_view_table__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeneralInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TableViewOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_parallels_for_middle_text_view_middle__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TextViewMiddleInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TextViewMiddleOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_file_text_segments_and_parallels_text_view_text_parallels__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TextParallelsInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["TextViewLeftOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_numbers_view_numbers_view_numbers__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeneralInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["NumbersViewOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_categories_for_numbers_view_numbers_view_categories__get: {
    parameters: {
      query: {
        /** @description Filename to be used */
        filename: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["MenuOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_external_links_links_external__get: {
    parameters: {
      query: {
        filename: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["LinksOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_counts_for_file_utils_count_matches__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CountMatchesInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["CountMatchesOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_folios_for_file_utils_folios__get: {
    parameters: {
      query: {
        /** @description File name of the text for which folios should be fetched. */
        filename: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["FolioOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_displayname_for_segmentnr_utils_displayname__get: {
    parameters: {
      query: {
        /** @description Segmentnr for which the displayname should be fetched. */
        segmentnr: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["DisplayNameOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_data_for_sidebar_menu_menudata__get: {
    parameters: {
      query: {
        /** @description language to be used */
        language: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["MenudataOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
