export const API_ROOT_URL = process.env.NEXT_PUBLIC_API_URL;
export const RESULTS_DOWNLOAD_ROOT_URL = process.env.NEXT_PUBLIC_DOWNLOAD_URL;
export const SEARCH_RESULTS_LIMIT = 200;
export const PARALLELS_RESULTS_LIMIT = 15000;
