FROM python:3.7.4-buster

RUN mkdir -p /opt/buddhanexus
WORKDIR /opt/buddhanexus
COPY */requirements-dataloader.txt requirements.txt
RUN pip install -r requirements.txt
COPY * /opt/buddhanexus/

# Keep container running
CMD tail -f /dev/null
WORKDIR /opt/buddhanexus/dataloader
