FROM python:3.8-bookworm

RUN mkdir -p /opt/buddhanexus
WORKDIR /opt/buddhanexus
COPY */requirements-dataloader.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -U setuptools
RUN pip install -U pylint
COPY . .
RUN pip install -e .

# Keep container running
CMD tail -f /dev/null
WORKDIR /opt/buddhanexus/dataloader
