FROM python:3.8-bookworm

WORKDIR /opt/buddhanexus

# Copy the entire project
COPY . .

# Install requirements
RUN pip install --upgrade pip
RUN pip install -r setup/requirements-fastapi.txt

# Install project in editable mode
RUN pip install -e .

# Install additional tools
RUN pip install -U setuptools pylint