import os

DB_NAME = os.environ["ARANGO_BASE_DB_NAME"]
ARANGO_USER = os.environ["ARANGO_USER"]
ARANGO_PASSWORD = os.environ["ARANGO_ROOT_PASSWORD"]
ARANGO_HOST = f"http://{os.environ['ARANGO_HOST']}:{os.environ['ARANGO_PORT']}"
DEFAULT_SOURCE_URL = os.environ["SOURCE_FILES_URL"]

LANG_TIBETAN = "tib"
LANG_SANSKRIT = "skt"
LANG_CHINESE = "chn"
LANG_PALI = "pli"
DEFAULT_LANGS = (LANG_CHINESE, LANG_SANSKRIT, LANG_TIBETAN, LANG_PALI)

COLLECTION_PARALLELS = "parallels"
COLLECTION_SEGMENTS = "segments"
COLLECTION_LANGUAGES = "languages"
COLLECTION_FILES = "files"
COLLECTION_MENU_COLLECTIONS = "menu_collections"
COLLECTION_MENU_CATEGORIES = "menu_categories"
COLLECTION_FILES_PARALLEL_COUNT = "files_parallel_count"
COLLECTION_CATEGORIES_PARALLEL_COUNT = "categories_parallel_count"

COLLECTION_NAMES = (
    COLLECTION_PARALLELS,
    COLLECTION_SEGMENTS,
    COLLECTION_LANGUAGES,
    COLLECTION_FILES,
    COLLECTION_MENU_COLLECTIONS,
    COLLECTION_MENU_CATEGORIES,
    COLLECTION_FILES_PARALLEL_COUNT,
    COLLECTION_CATEGORIES_PARALLEL_COUNT,
)

# Edge collections
EDGE_COLLECTION_LANGUAGE_HAS_COLLECTIONS = "language_has_collections"
EDGE_COLLECTION_COLLECTION_HAS_CATEGORIES = "collection_has_categories"
EDGE_COLLECTION_CATEGORY_HAS_FILES = "category_has_files"
EDGE_COLLECTION_FILE_HAS_SEGMENTS = "file_has_segments"

EDGE_COLLECTION_NAMES = (
    EDGE_COLLECTION_LANGUAGE_HAS_COLLECTIONS,
    EDGE_COLLECTION_COLLECTION_HAS_CATEGORIES,
    EDGE_COLLECTION_CATEGORY_HAS_FILES,
    EDGE_COLLECTION_FILE_HAS_SEGMENTS,
)

GRAPH_COLLECTIONS_CATEGORIES = "collections_categories"
GRAPH_FILES_SEGMENTS = "files_segments"

COLLECTION_REGEX = "^(pli-tv-b[ui]-vb|[A-Z]+[0-9]+|[a-z\-]+)"
