COLLECTION_SEGMENTS = "segments"
COLLECTION_PARALLELS = "parallels"
COLLECTION_FILES = "files"
COLLECTION_MENU_COLLECTIONS = "menu-collections"
COLLECTION_MENU_CATEGORIES = "menu-categories"

COLLECTION_NAMES = (
    COLLECTION_PARALLELS,
    COLLECTION_SEGMENTS,
    COLLECTION_FILES,
    COLLECTION_MENU_COLLECTIONS,
    COLLECTION_MENU_CATEGORIES,
)
