name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run TypeScript compiler
        run: tsc
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
